# Path to your custom styles folder
StylesPath = .github/styles

# The lowest level of error to show (suggestion, warning, or error)
MinAlertLevel = suggestion

# Only check Markdown files
[*.md]
# Use the rules inside the "Demo" folder
BasedOnStyles = Demo