# This specifies where Vale will download the package to.
# Make sure this directory exists or create it!
StylesPath = styles

# The minimum level of alert to report (suggestion, warning, or error).
MinAlertLevel = suggestion

# Tells Vale to download the official Microsoft package
Packages = Microsoft

# Applies the rules to all Markdown and text files
[*.{md,txt}]
BasedOnStyles = Vale, Microsoft