name: Check Links

on:
  push:
    branches: [main, master]
  workflow_dispatch: 

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # We define the rules DIRECTLY here so we don't need lychee.toml
          args: >
            --verbose
            --no-progress
            --exclude-mail
            --exclude-all-private
            "./**/*.md"
          failIfEmpty: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}